---
title: ""
output: html_document
---

```{r setup, include=FALSE, echo=FALSE}
system("touch restart.txt", intern = FALSE)
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(htmltools)
library(plotly)
library(shiny)
library(stringr)

# dat <- readRDS("current_signatories.rds")
dat <- readRDS("/home/jacobmalcom/cronjobs/conservation-funding/current_signatories.rds")

```

### Scientists Signatories:
```{r echo=FALSE} 
h1(length(dat$category))
```

----

### Signatories by Country (Top 10)

```{r echo=FALSE} 
cnt <- table(dat$country) %>%
    sort(decreasing = TRUE) %>%
    head(10) %>%
    as.data.frame()
plot_ly(data = cnt, x = ~Var1, y = ~Freq, type = "bar",
        marker = list(color = "#C41230")) %>%
  layout(xaxis = list(title = "", size = 18),
         yaxis = list(title = "# Signatories", size = 18))
```

### Signatories by State (Top 10)

```{r echo=FALSE}
ste <- table(dat$state) %>%
  sort(decreasing = TRUE) %>%
  head(10) %>%
  as.data.frame()
plot_ly(data = ste, x = ~Var1, y = ~Freq, type = "bar",
        marker = list(color = "#E36F1E")) %>%
  layout(xaxis = list(title = "", size = 18),
         yaxis = list(title = "# Signatories", size = 18))
```

### Signatories by Degree

```{r echo=FALSE}
ph_pat <- "PhD|DVM|DPhil|Post-doc|Postdoc|Ph D|MD|Dr|Doctor|Doctorado"
ms_pat <- "Master|MS|MA|MBA|MPH" 
dat$degree_short <- lapply(dat$degree, function(x){
  x <- str_replace_all(x, "\\.", "")
  phd <- length(grep(x, pattern = ph_pat, ignore.case = TRUE)) > 0
  mas <- length(grep(x, pattern = ms_pat, ignore.case = TRUE)) > 0
  if_else(phd, "Doctorate", if_else(
    mas, "Master's", "Other"))
}) %>% unlist()

deg <- table(dat$degree_short) %>%
  as.data.frame()
plot_ly(data = deg, x = ~Var1, y = ~Freq, type = "bar",
        marker = list(color = "#005596")) %>%
  layout(xaxis = list(title = "", size = 18),
         yaxis = list(title = "# Signatories", size = 18))
```